
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-task-02
data:
  mongodb: mongodb://localhost:27017/material
  username: Alice
---
apiVersion: v1
kind: Pod
metadata:
  name: task-02
  labels:
    app: task-02
spec:
  containers:
  - name: task-02
    image: task-02:v1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9000
    env:
        - name: MONGODB_URI
          valueFrom:
              configMapKeyRef:
                  name: configmap-task-02
                  key: mongodb
    volumeMounts:
        - name: config
          mountPath: /config
  volumes:
      - name: config
        configMap:
          name: configmap-task-02
          items:
              - key: username
                path: username
---
apiVersion: v1
kind: Service
metadata:
  name: task-02
spec:
  type: NodePort
  selector:
    app: task-02
  ports:
  - port: 9000
    targetPort: 9000
